/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htr;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author josips
 */
public class MojiTicketi extends javax.swing.JFrame {

    Connection Conn;
    int myUserID;
    int rowClickedInt;

    //Spajanje na bazu
    IzvrsavanjeSkriptiNaBazi CALIzb = new IzvrsavanjeSkriptiNaBazi();
    ResultSet RS = null;

    /**
     * Creates new form MojiTicketi
     */
    public MojiTicketi(Connection conn, int MyUserID) {
        this.Conn = conn;
        this.myUserID = MyUserID;

        initComponents();
        PocetnePostavke();
    }

    private void PocetnePostavke() {
        PunjenjeTablice();
        AddActionListener();

        //Postavljanje ROW-HEIGHT tablice
        myTicketTable.setRowHeight(22);
    }

    private void PunjenjeTablice() {
        try {
            //Nogomet
            RS = CALIzb.main(Conn, "select F08IDT ID, F08ULO Ulog, F08ISP Isplata, F08DOB Dobitak, F08BON Bonus, F08TEC Tečaj, F08PDV Porez, F08DVT 'Datum i vrijeme uplate' from ticket where F08UID = '" + myUserID + "'");
            myTicketTable.setModel(DbUtils.resultSetToTableModel(RS));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void AddActionListener() {

        //Dohvacanje row i col numbera
        myTicketTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    String rowClicked;

                    //Get row to int
                    rowClicked = myTicketTable.getValueAt(myTicketTable.getSelectedRow(), 0).toString();
                    rowClickedInt = Integer.parseInt(rowClicked);
                    if (rowClickedInt > 0) {
                        RS = CALIzb.main(Conn, "select F081PAR1 Domacin, F081PAR2 Protivnik, F081TIP TIP, F081KOEF KOEFICIJENT from ticket_parovi where F081IDU = '" + rowClickedInt + "'  ORDER BY F018DVT ASC");
                        tbl_PrikazParova.setModel(DbUtils.resultSetToTableModel(RS));
                    }

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        myTicketTable = new javax.swing.JTable();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        pic_Ticket = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_PrikazParova = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        myTicketTable.setBackground(new java.awt.Color(204, 204, 204));
        myTicketTable.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        myTicketTable.setForeground(new java.awt.Color(255, 255, 255));
        myTicketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ulog", "Isplata", "Dobitak", "Bonus", "Tecaj", "Porez", "Datum i vrijeme uplate"
            }
        ));
        myTicketTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(myTicketTable);

        mainPanel.setBackground(new java.awt.Color(26, 83, 92));
        mainPanel.setForeground(new java.awt.Color(26, 83, 92));
        mainPanel.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pregled ticketa");

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/rsz_exit.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        pic_Ticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/pic_ticket.png"))); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic_Ticket)
                .addGap(316, 316, 316)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblExit)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pic_Ticket)
                            .addComponent(lblExit)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_PrikazParova.setBackground(new java.awt.Color(204, 204, 204));
        tbl_PrikazParova.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tbl_PrikazParova.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Domacin", "Protivnik", "Tip", "Koeficijent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_PrikazParova.setEnabled(false);
        jScrollPane2.setViewportView(tbl_PrikazParova);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable myTicketTable;
    private javax.swing.JLabel pic_Ticket;
    private javax.swing.JTable tbl_PrikazParova;
    // End of variables declaration//GEN-END:variables
}
