/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htr;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.Timer;
import java.util.Calendar;
import java.util.TimeZone;

/**
 *
 * @author josips
 */
public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    // PARAMETRI 
    private Connection conn;
    int CharUserLeft = 20;
    boolean userPostoji;
    boolean PasswordNijeIsti;
    int godRazlika = 0;
    int godinaRodenja;
    int mjesecRodenja;
    int danRodenja;
    int MyIDNumber = 0;

    // Prvo Punjenje
    int MyFirstLogUsername = 0;
    int MyFirstLogName = 0;
    int MyFirstLogSurname = 0;
    int MyFirstLogPass = 0;
    int MyFirstLogPassSec = 0;
    int MyFirstLogMail = 0;
    int MyFirstLogBrTel = 0;
    int MyFirstLogDrzava = 0;
    int MyFirstLogGradRodenja = 0;
    int MyFirstLogAdresa = 0;
    int MyFirstLogPostBroj = 0;

    //Spajanje na bazu
    ResultSet RS = null;
    IzvrsavanjeSkriptiNaBazi CALIzb = new IzvrsavanjeSkriptiNaBazi();

    /**
     * Creates new form LoginForm
     *
     * @param Conn
     */
    public RegistrationForm(Connection Conn) {
        this.conn = Conn;
        initComponents();
        userNotFound.setVisible(false);
        userFound.setVisible(false);
        img_PasswordCheck.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanel1 = new javax.swing.JPanel();
        txt_BrTel = new javax.swing.JPanel();
        txt_KorisnickoIme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_Ime = new javax.swing.JTextField();
        txt_Prezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        txt_PonoviPassword = new javax.swing.JPasswordField();
        txt_Mail = new javax.swing.JTextField();
        txt_BrojTele = new javax.swing.JTextField();
        txt_Drzava = new javax.swing.JTextField();
        txt_GradRode = new javax.swing.JTextField();
        txt_Adresa = new javax.swing.JTextField();
        txt_PBR = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        lbl_MainRegistration = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_BrojacUserChar = new javax.swing.JLabel();
        lbl_maxUserChar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        myYearBirth = new com.toedter.calendar.JYearChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        myDayBirth = new javax.swing.JComboBox<>();
        txt_agreem = new javax.swing.JLabel();
        txt_agreem1 = new javax.swing.JLabel();
        txt_agreem2 = new javax.swing.JLabel();
        cbx_AgreeUSR = new javax.swing.JCheckBox();
        myMonthBirth = new javax.swing.JComboBox<>();
        lbl_ExitReg = new javax.swing.JLabel();
        userFound = new javax.swing.JLabel();
        userNotFound = new javax.swing.JLabel();
        img_PasswordCheck = new javax.swing.JLabel();
        img_Registration = new javax.swing.JLabel();
        btn_Registriraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("formRegistration"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(66, 76, 82));

        txt_BrTel.setBackground(new java.awt.Color(0, 126, 167));
        txt_BrTel.setForeground(new java.awt.Color(255, 255, 0));
        txt_BrTel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        txt_KorisnickoIme.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_KorisnickoIme.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_KorisnickoIme.setText("example");
        txt_KorisnickoIme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_KorisnickoImeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_KorisnickoImeFocusLost(evt);
            }
        });
        txt_KorisnickoIme.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_KorisnickoImePropertyChange(evt);
            }
        });
        txt_KorisnickoIme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_KorisnickoImeKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KORISNIČKO IME");

        txt_Ime.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Ime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Ime.setText("example");
        txt_Ime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_ImeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ImeFocusLost(evt);
            }
        });
        txt_Ime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ImeKeyTyped(evt);
            }
        });

        txt_Prezime.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Prezime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Prezime.setText("example");
        txt_Prezime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PrezimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PrezimeFocusLost(evt);
            }
        });
        txt_Prezime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PrezimeKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("IME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PREZIME");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ŠIFRA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PONOVLJENA ŠIFRA");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MAIL");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GODINA ROĐENJA");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("GRAD ROĐENJA");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DRŽAVA");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ADRESA");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("POŠTANSKI BROJ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("BROJ TELEFONA");

        txt_Password.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Password.setText("mytestpassword");
        txt_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PasswordFocusLost(evt);
            }
        });

        txt_PonoviPassword.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_PonoviPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_PonoviPassword.setText("mytestpassword");
        txt_PonoviPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PonoviPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PonoviPasswordFocusLost(evt);
            }
        });

        txt_Mail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Mail.setText("example@example.com");
        txt_Mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_MailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MailFocusLost(evt);
            }
        });

        txt_BrojTele.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_BrojTele.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_BrojTele.setText("111111111");
        txt_BrojTele.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_BrojTeleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_BrojTeleFocusLost(evt);
            }
        });
        txt_BrojTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BrojTeleActionPerformed(evt);
            }
        });
        txt_BrojTele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_BrojTeleKeyTyped(evt);
            }
        });

        txt_Drzava.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Drzava.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Drzava.setText("example");
        txt_Drzava.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_DrzavaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DrzavaFocusLost(evt);
            }
        });
        txt_Drzava.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DrzavaKeyTyped(evt);
            }
        });

        txt_GradRode.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_GradRode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_GradRode.setText("example");
        txt_GradRode.setToolTipText("");
        txt_GradRode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_GradRodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_GradRodeFocusLost(evt);
            }
        });
        txt_GradRode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_GradRodeKeyTyped(evt);
            }
        });

        txt_Adresa.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Adresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Adresa.setText("example");
        txt_Adresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_AdresaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_AdresaFocusLost(evt);
            }
        });

        txt_PBR.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_PBR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_PBR.setText("11111");
        txt_PBR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_PBRFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PBRFocusLost(evt);
            }
        });
        txt_PBR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PBRKeyTyped(evt);
            }
        });

        jLabel13.setToolTipText("");

        lbl_MainRegistration.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lbl_MainRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lbl_MainRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_MainRegistration.setText("REGISTRATION");

        lbl_BrojacUserChar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl_BrojacUserChar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BrojacUserChar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_BrojacUserChar.setText("20");

        lbl_maxUserChar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl_maxUserChar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_maxUserChar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_maxUserChar.setText("/ 20");

        myYearBirth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                myYearBirthFocusLost(evt);
            }
        });
        myYearBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                myYearBirthKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("MJESEC ROĐENJA");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DAN ROĐENJA");

        myDayBirth.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        myDayBirth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        txt_agreem.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txt_agreem.setForeground(new java.awt.Color(255, 255, 255));
        txt_agreem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_agreem.setText("Korištenjem ove aplikacije potvrđujete da ste stariji od 18 godina, ");

        txt_agreem1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txt_agreem1.setForeground(new java.awt.Color(255, 255, 255));
        txt_agreem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_agreem1.setText("odnosno da imate dovoljno godina za klađenje u državi iz koje pristupate našoj stranici");

        txt_agreem2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txt_agreem2.setForeground(new java.awt.Color(255, 255, 255));
        txt_agreem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_agreem2.setText("Slažem se te se želim registrirati:");

        cbx_AgreeUSR.setBackground(new java.awt.Color(0, 126, 167));
        cbx_AgreeUSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_AgreeUSRActionPerformed(evt);
            }
        });

        myMonthBirth.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        myMonthBirth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        lbl_ExitReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/rsz_exit.png"))); // NOI18N
        lbl_ExitReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ExitRegMouseClicked(evt);
            }
        });

        userFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/notvaild.png"))); // NOI18N

        userNotFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/vaild.png"))); // NOI18N
        userNotFound.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        img_PasswordCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/notvaild.png"))); // NOI18N
        img_PasswordCheck.setToolTipText("");

        img_Registration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/user_registration.png"))); // NOI18N

        btn_Registriraj.setBackground(new java.awt.Color(0, 126, 167));
        btn_Registriraj.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btn_Registriraj.setForeground(new java.awt.Color(255, 255, 0));
        btn_Registriraj.setText("Registriraj se");
        btn_Registriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txt_BrTelLayout = new javax.swing.GroupLayout(txt_BrTel);
        txt_BrTel.setLayout(txt_BrTelLayout);
        txt_BrTelLayout.setHorizontalGroup(
            txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_BrTelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txt_BrTelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txt_BrTelLayout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_BrTelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(img_Registration)
                                .addGap(253, 253, 253)
                                .addComponent(lbl_ExitReg)
                                .addContainerGap())))
                    .addGroup(txt_BrTelLayout.createSequentialGroup()
                        .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BrTelLayout.createSequentialGroup()
                                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Adresa)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Drzava, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(txt_BrTelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_PBR)))
                                    .addGroup(txt_BrTelLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(txt_GradRode))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BrTelLayout.createSequentialGroup()
                                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Mail, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                    .addComponent(txt_BrojTele)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BrTelLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BrTelLayout.createSequentialGroup()
                                    .addComponent(txt_KorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_BrojacUserChar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_maxUserChar)
                                    .addGap(18, 18, 18)
                                    .addComponent(userFound)
                                    .addGap(26, 26, 26)
                                    .addComponent(userNotFound))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BrTelLayout.createSequentialGroup()
                                    .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(myYearBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(myDayBirth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(myMonthBirth, 0, 92, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                .addComponent(txt_agreem1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_agreem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BrTelLayout.createSequentialGroup()
                                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(img_PasswordCheck)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_PonoviPassword))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BrTelLayout.createSequentialGroup()
                                    .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(txt_BrTelLayout.createSequentialGroup()
                                            .addComponent(txt_Ime)
                                            .addGap(18, 18, 18))
                                        .addGroup(txt_BrTelLayout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_Prezime)))))
                        .addGap(8, 8, 8))))
            .addGroup(txt_BrTelLayout.createSequentialGroup()
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txt_BrTelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(txt_agreem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx_AgreeUSR))
                    .addGroup(txt_BrTelLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btn_Registriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_BrTelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_MainRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        txt_BrTelLayout.setVerticalGroup(
            txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_BrTelLayout.createSequentialGroup()
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txt_BrTelLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img_Registration)
                            .addComponent(lbl_ExitReg)))
                    .addGroup(txt_BrTelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lbl_MainRegistration)
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_BrojacUserChar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userFound, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_KorisnickoIme)
                    .addComponent(lbl_maxUserChar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNotFound, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Prezime, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Ime, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_PonoviPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img_PasswordCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_BrojTele, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Drzava, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_GradRode, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_PBR, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txt_Adresa))
                .addGap(18, 18, 18)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myYearBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_BrTelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(myMonthBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(myDayBirth, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_agreem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_agreem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_BrTelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_agreem2)
                    .addComponent(cbx_AgreeUSR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Registriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_BrTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_BrTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_AgreeUSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_AgreeUSRActionPerformed
        // TODO add your handling code here:
        if (cbx_AgreeUSR.isSelected()) {

            //BIRTH DAY, MONTH, YEAR
            danRodenja = Integer.parseInt(myDayBirth.getSelectedItem().toString());
            mjesecRodenja = Integer.parseInt(myMonthBirth.getSelectedItem().toString());
            godinaRodenja = myYearBirth.getValue();

            //CURRENT DAY, MONTH, YEAR
            Calendar calendar = Calendar.getInstance(TimeZone.getDefault());
            int currentmonth = calendar.get(Calendar.MONTH) + 1;
            int currentYear = calendar.get(Calendar.YEAR);
            int dayOcurrentDay = calendar.get(Calendar.DAY_OF_MONTH);

            godRazlika = currentYear - godinaRodenja;
            if (currentmonth < mjesecRodenja) {
                godRazlika -= 1;
            } else if (currentmonth == mjesecRodenja) {
                if (dayOcurrentDay < danRodenja) {
                    godRazlika -= 1;
                }
            }

            if (godRazlika < 18) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Imate manje od 18 godina!");
                Timer timer = new Timer(2000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
            }

            if (godRazlika > 18) {
                setFieldsDisabled();
            }

            if ((txt_KorisnickoIme.getText().equals("") || txt_KorisnickoIme.getText().equals("example"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite korisnicko ime!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_Ime.getText().equals("") || txt_Ime.getText().equals("example"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite ime!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_Prezime.getText().equals("") || txt_Prezime.getText().equals("example"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite prezime!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_Password.getText().equals("") || txt_Password.getText().equals("mytestpassword"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite šifru!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_PonoviPassword.getText().equals("") || txt_PonoviPassword.getText().equals("mytestpassword"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite šifru!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_Mail.getText().equals("") || txt_Mail.getText().equals("example@example.com"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite mail!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_BrojTele.getText().equals("") || txt_BrojTele.getText().equals("111111111"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite broj telefona!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_Drzava.getText().equals("") || txt_Drzava.getText().equals("example"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite drzavu!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_GradRode.getText().equals("") || txt_GradRode.getText().equals("example"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite grad rodenja!");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_Adresa.getText().equals("") || txt_Adresa.getText().equals("example"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite adresu");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

            if ((txt_PBR.getText().equals("") || txt_PBR.getText().equals("11111"))) {
                cbx_AgreeUSR.setSelected(false);
                lbl_MainRegistration.setText("Popunite postanski broj");
                Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                setFieldsEnabled();
            }

        } else {
            setFieldsEnabled();
        }
    }//GEN-LAST:event_cbx_AgreeUSRActionPerformed

    private void txt_PonoviPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PonoviPasswordFocusLost
        // TODO add your handling code here:
        // Provjera passworda
        if (Arrays.equals(txt_PonoviPassword.getPassword(), txt_Password.getPassword())) {
            img_PasswordCheck.setVisible(false);
            PasswordNijeIsti = true;
        } else {
            img_PasswordCheck.setVisible(true);
            PasswordNijeIsti = false;

            lbl_MainRegistration.setText("Unesite jednake šifre!");
            Timer timer = new Timer(2000, e -> lbl_MainRegistration.setText("REGISTRATION"));
            timer.setRepeats(false);
            timer.start();
            userPostoji = true;
        }
    }//GEN-LAST:event_txt_PonoviPasswordFocusLost

    public void setFieldsEnabled() {
        txt_KorisnickoIme.setEditable(true);
        txt_Ime.setEditable(true);
        txt_Prezime.setEditable(true);
        txt_Password.setEditable(true);
        txt_PonoviPassword.setEditable(true);
        txt_Mail.setEditable(true);
        txt_BrojTele.setEditable(true);
        txt_Drzava.setEditable(true);
        txt_GradRode.setEditable(true);
        txt_Adresa.setEditable(true);
        txt_PBR.setEditable(true);
        myYearBirth.setEnabled(true);
        myDayBirth.setEnabled(true);
        myMonthBirth.setEnabled(true);
    }

    public void setFieldsDisabled() {
        txt_KorisnickoIme.setEditable(false);
        txt_Ime.setEditable(false);
        txt_Prezime.setEditable(false);
        txt_Password.setEditable(false);
        txt_PonoviPassword.setEditable(false);
        txt_Mail.setEditable(false);
        txt_BrojTele.setEditable(false);
        txt_Drzava.setEditable(false);
        txt_GradRode.setEditable(false);
        txt_Adresa.setEditable(false);
        txt_PBR.setEditable(false);
        myYearBirth.setEnabled(false);
        myDayBirth.setEnabled(false);
        myMonthBirth.setEnabled(false);
    }


    private void txt_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PasswordFocusLost
        // TODO add your handling code here:
        if (Arrays.equals(txt_PonoviPassword.getPassword(), txt_Password.getPassword())) {
            img_PasswordCheck.setVisible(false);
            PasswordNijeIsti = true;
        } else {
            img_PasswordCheck.setVisible(true);
            PasswordNijeIsti = false;

            lbl_MainRegistration.setText("Unesite jednake šifre!");
            Timer timer = new Timer(2000, e -> lbl_MainRegistration.setText("REGISTRATION"));
            timer.setRepeats(false);
            timer.start();
            userPostoji = true;
        }

    }//GEN-LAST:event_txt_PasswordFocusLost

    private void txt_KorisnickoImeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_KorisnickoImeKeyPressed
        // TODO add your handling code here:
        // Brojac UserName Charactera
        CharUserLeft = txt_KorisnickoIme.getText().length();
        CharUserLeft += 1;
        lbl_BrojacUserChar.setText(Integer.toString(CharUserLeft));

        if (CharUserLeft > 20) {
            lbl_BrojacUserChar.setForeground(Color.RED);
        } else {
            lbl_BrojacUserChar.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_txt_KorisnickoImeKeyPressed

    private void txt_KorisnickoImePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_KorisnickoImePropertyChange

    }//GEN-LAST:event_txt_KorisnickoImePropertyChange

    private void txt_KorisnickoImeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_KorisnickoImeFocusLost
        // TODO add your handling code here:
        try {
            RS = CALIzb.main(conn, "select * from users where F01USR = '" + txt_KorisnickoIme.getText().trim() + "'");

            if (RS.next() || txt_KorisnickoIme.getText().isEmpty()) {
                userFound.setVisible(true);
                userNotFound.setVisible(false);

                lbl_MainRegistration.setText("Korisnik postoji!");
                Timer timer = new Timer(2000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                userPostoji = true;

            } else {
                userNotFound.setVisible(true);
                userFound.setVisible(false);
                userPostoji = false;

            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_txt_KorisnickoImeFocusLost

    private void lbl_ExitRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ExitRegMouseClicked
        // TODO add your handling code here:
        LoginForm CALLogin = new LoginForm(conn);
        CALLogin.setLocationRelativeTo(null);
        CALLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_ExitRegMouseClicked

    private void txt_BrojTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BrojTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BrojTeleActionPerformed

    private void btn_RegistrirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrirajActionPerformed
        LoginForm CALLogin = new LoginForm(conn);
        CALLogin.setLocationRelativeTo(null);
        if (PasswordNijeIsti && cbx_AgreeUSR.isSelected()) {
            try {
                //Dohvacanje zadnjeg ID-a
                RS = CALIzb.main(conn, "DECLARE @lastNumb int; set @lastNumb = (SELECT TOP 1 F01ID FROM users ORDER BY F01ID DESC); select F01ID from users where F01ID = @lastNumb");
                while (RS.next()) {
                    MyIDNumber = RS.getInt("F01ID");
                    MyIDNumber += 1;
                }
                if (MyIDNumber == 0) {
                    MyIDNumber += 1;
                }
                //Postavljanje datuma rodenja
                danRodenja = Integer.parseInt(myDayBirth.getSelectedItem().toString());
                mjesecRodenja = Integer.parseInt(myMonthBirth.getSelectedItem().toString());
                godinaRodenja = myYearBirth.getValue();
                String datumRodenja = Integer.toString(godinaRodenja) + "-" + Integer.toString(danRodenja) + "-" + Integer.toString(mjesecRodenja);
                //Kreiranje korisnika
                RS = CALIzb.main(conn, "INSERT INTO Users VALUES ('" + MyIDNumber + "','" + txt_KorisnickoIme.getText().trim() + "','" + txt_Ime.getText().trim() + "','" + txt_Prezime.getText().trim() + "','" + txt_Password.getText().trim() + "','" + txt_Mail.getText().trim() + "','" + datumRodenja.trim() + "','" + txt_GradRode.getText().trim() + "','" + txt_Drzava.getText().trim() + "','" + txt_Adresa.getText().trim() + "','" + txt_PBR.getText().trim() + "','" + txt_BrojTele.getText().trim() + "','1'," + "GETDATE ( )  " + "," + "GETDATE ( )  " + ",'1','0')");

                //Dohvacanje zadnjeg ID-a za sredstava na racun
                int myLastIDSredstva = 0;

                RS = CALIzb.main(conn, "DECLARE @lastNumb int; set @lastNumb = (SELECT TOP 1 F03IDS FROM User_Stanje ORDER BY F03IDS DESC); select F03IDS from User_Stanje where F03IDS = @lastNumb");
                while (RS.next()) {
                    myLastIDSredstva = RS.getInt("F03IDS");
                    myLastIDSredstva += 1;
                }
                if (myLastIDSredstva == 0) {
                    myLastIDSredstva += 1;
                }

                //Dodavanje besplatnih sredstava na racun
                RS = CALIzb.main(conn, "INSERT INTO User_Stanje VALUES ('" + myLastIDSredstva + "','100','100','0','Bonus 100','" + MyIDNumber + "')");

                PopError CALError = new PopError();
                CALError.infoBox("Registracija uspješna!", "Success!");

                CALLogin.setVisible(true);
                dispose();

            } catch (Exception e) {

            }
        } else {
            if (!PasswordNijeIsti) {
                lbl_MainRegistration.setText("Šifre nisu iste!");
                Timer timer = new Timer(2000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
            } else if (!cbx_AgreeUSR.isSelected()) {
                lbl_MainRegistration.setText("Niste prihvatili sporazume!");
                Timer timer = new Timer(2000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
            }
        }
    }//GEN-LAST:event_btn_RegistrirajActionPerformed

    private void txt_KorisnickoImeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_KorisnickoImeFocusGained
        // TODO add your handling code here:
        if (MyFirstLogUsername == 0) {
            txt_KorisnickoIme.setText("");
            MyFirstLogUsername++;
        }
    }//GEN-LAST:event_txt_KorisnickoImeFocusGained

    private void txt_ImeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ImeFocusGained
        // TODO add your handling code here:
        if (MyFirstLogName == 0) {
            txt_Ime.setText("");
            MyFirstLogName++;
        }
    }//GEN-LAST:event_txt_ImeFocusGained

    private void txt_PrezimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PrezimeFocusGained
        // TODO add your handling code here:
        if (MyFirstLogSurname == 0) {
            txt_Prezime.setText("");
            MyFirstLogSurname++;
        }
    }//GEN-LAST:event_txt_PrezimeFocusGained

    private void txt_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PasswordFocusGained
        // TODO add your handling code here:
        if (MyFirstLogPass == 0) {
            txt_Password.setText("");
            MyFirstLogPass++;
        }
    }//GEN-LAST:event_txt_PasswordFocusGained

    private void txt_PonoviPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PonoviPasswordFocusGained
        if (MyFirstLogPassSec == 0) {
            txt_PonoviPassword.setText("");
            MyFirstLogPassSec++;
        }
    }//GEN-LAST:event_txt_PonoviPasswordFocusGained

    private void txt_MailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MailFocusGained
        // TODO add your handling code here:
        if (MyFirstLogMail == 0) {
            txt_Mail.setText("");
            MyFirstLogMail++;
        }
    }//GEN-LAST:event_txt_MailFocusGained

    private void txt_BrojTeleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BrojTeleFocusGained
        if (MyFirstLogBrTel == 0) {
            txt_BrojTele.setText("");
            MyFirstLogBrTel++;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BrojTeleFocusGained

    private void txt_DrzavaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DrzavaFocusGained
        // TODO add your handling code here:
        if (MyFirstLogDrzava == 0) {
            txt_Drzava.setText("");
            MyFirstLogDrzava++;
        }
    }//GEN-LAST:event_txt_DrzavaFocusGained

    private void txt_GradRodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_GradRodeFocusGained
        // TODO add your handling code here:
        if (MyFirstLogGradRodenja == 0) {
            txt_GradRode.setText("");
            MyFirstLogGradRodenja++;
        }
    }//GEN-LAST:event_txt_GradRodeFocusGained

    private void txt_AdresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AdresaFocusGained
        // TODO add your handling code here:
        if (MyFirstLogAdresa == 0) {
            txt_Adresa.setText("");
            MyFirstLogAdresa++;
        }
    }//GEN-LAST:event_txt_AdresaFocusGained

    private void txt_PBRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PBRFocusGained
        // TODO add your handling code here:
        if (MyFirstLogPostBroj == 0) {
            txt_PBR.setText("");
            MyFirstLogPostBroj++;
        }
    }//GEN-LAST:event_txt_PBRFocusGained

    private void txt_ImeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ImeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ImeFocusLost

    private void txt_PrezimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PrezimeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PrezimeFocusLost

    private void txt_MailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MailFocusLost
        // TODO add your handling code here:

        if (!txt_Mail.getText().toLowerCase().contains("@")) {
            lbl_MainRegistration.setText("Mail nije ispravan!");
            Timer timer = new Timer(1000, e -> lbl_MainRegistration.setText("REGISTRATION"));
            timer.setRepeats(false);
            timer.start();
            txt_Mail.setText(null);
        }

        try {
            RS = CALIzb.main(conn, "select * from users where F01EMA = '" + txt_Mail.getText().trim() + "'");

            if (RS.next() || txt_Mail.getText().isEmpty()) {

                lbl_MainRegistration.setText("Mail postoji!");
                txt_Mail.setText("");
                Timer timer = new Timer(2000, e -> lbl_MainRegistration.setText("REGISTRATION"));
                timer.setRepeats(false);
                timer.start();
                userPostoji = true;

            } else {
                
            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_txt_MailFocusLost

    private void txt_BrojTeleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BrojTeleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BrojTeleFocusLost

    private void txt_DrzavaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DrzavaFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_DrzavaFocusLost

    private void txt_GradRodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_GradRodeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GradRodeFocusLost

    private void txt_AdresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_AdresaFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_AdresaFocusLost

    private void txt_PBRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PBRFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PBRFocusLost

    private void myYearBirthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_myYearBirthFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_myYearBirthFocusLost

    private void txt_BrojTeleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BrojTeleKeyTyped
        // TODO add your handling code here:
        ZabraniSlova(evt);
    }//GEN-LAST:event_txt_BrojTeleKeyTyped

    private void txt_PBRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PBRKeyTyped
        // TODO add your handling code here:
        ZabraniSlova(evt);
    }//GEN-LAST:event_txt_PBRKeyTyped

    private void myYearBirthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_myYearBirthKeyTyped

    }//GEN-LAST:event_myYearBirthKeyTyped

    private void txt_ImeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ImeKeyTyped
        // TODO add your handling code here:
        ZabraniBrojeve(evt);
    }//GEN-LAST:event_txt_ImeKeyTyped

    private void txt_PrezimeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PrezimeKeyTyped
        // TODO add your handling code here:
        ZabraniBrojeve(evt);
    }//GEN-LAST:event_txt_PrezimeKeyTyped

    private void txt_DrzavaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DrzavaKeyTyped
        // TODO add your handling code here:
        ZabraniBrojeve(evt);
    }//GEN-LAST:event_txt_DrzavaKeyTyped

    private void txt_GradRodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GradRodeKeyTyped
        // TODO add your handling code here:
        ZabraniBrojeve(evt);
    }//GEN-LAST:event_txt_GradRodeKeyTyped

    public void ZabraniBrojeve(java.awt.event.KeyEvent evt) {
        char vChar = evt.getKeyChar();
        if ((Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }

    public void ZabraniSlova(java.awt.event.KeyEvent evt) {
        char vChar = evt.getKeyChar();
        if ((!Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Registriraj;
    private javax.swing.JCheckBox cbx_AgreeUSR;
    private javax.swing.JLabel img_PasswordCheck;
    private javax.swing.JLabel img_Registration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_BrojacUserChar;
    private javax.swing.JLabel lbl_ExitReg;
    private javax.swing.JLabel lbl_MainRegistration;
    private javax.swing.JLabel lbl_maxUserChar;
    private javax.swing.JComboBox<String> myDayBirth;
    private javax.swing.JComboBox<String> myMonthBirth;
    private com.toedter.calendar.JYearChooser myYearBirth;
    private javax.swing.JTextField txt_Adresa;
    private javax.swing.JPanel txt_BrTel;
    private javax.swing.JTextField txt_BrojTele;
    private javax.swing.JTextField txt_Drzava;
    private javax.swing.JTextField txt_GradRode;
    private javax.swing.JTextField txt_Ime;
    private javax.swing.JTextField txt_KorisnickoIme;
    private javax.swing.JTextField txt_Mail;
    private javax.swing.JTextField txt_PBR;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JPasswordField txt_PonoviPassword;
    private javax.swing.JTextField txt_Prezime;
    private javax.swing.JLabel txt_agreem;
    private javax.swing.JLabel txt_agreem1;
    private javax.swing.JLabel txt_agreem2;
    private javax.swing.JLabel userFound;
    private javax.swing.JLabel userNotFound;
    // End of variables declaration//GEN-END:variables
}
