/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htr;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author josips
 */
public class UIOdobrenje extends javax.swing.JFrame {

    Connection Conn;
    int myUserID = 0;
    int rowClickedInt;
    double UserBalance;
    String userIme;
    String userPrezime;
    String userUsername;
    int myNextID = 0;
    boolean naCekanju = false;

    //Spajanje na bazu
    IzvrsavanjeSkriptiNaBazi CALIzb = new IzvrsavanjeSkriptiNaBazi();
    ResultSet RS = null;

    /**
     * Creates new form UIOdobrenje
     */
    public UIOdobrenje(Connection conn, int MyUserID, double userBalance) {
        this.Conn = conn;
        this.myUserID = MyUserID;
        this.UserBalance = userBalance;

        initComponents();

        PocetnoPodesavanje();
    }

    private void PocetnoPodesavanje() {

        //Hvatanje usera
        if (myUserID != 0) {
            GetUser(myUserID);
            PunjenjeTablica();
        }
    }

    public void ZabraniSlova(java.awt.event.KeyEvent evt) {
        char vChar = evt.getKeyChar();
        if ((!Character.isDigit(vChar)
                || (vChar == KeyEvent.VK_BACK_SPACE)
                || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }

    private void GetUser(int userID) {

        try {
            RS = CALIzb.main(Conn, "select F01IME, F01PRE from users where F01ID = '" + userID + "'");
            if (!RS.next()) {
                txt_UserID.setText("");
                lbl_Ime.setText("");
                lbl_Prezime.setText("");
            } else {
                RS = CALIzb.main(Conn, "select F01IME, F01PRE, F01USR from users where F01ID = '" + userID + "'");
                while (RS.next()) {
                    userIme = RS.getString("F01IME");
                    userPrezime = RS.getString("F01PRE");
                    userUsername = RS.getString("F01USR");

                    txt_UserID.setText(Integer.toString(userID));
                    lbl_Ime.setText(userIme);
                    lbl_Prezime.setText(userPrezime);

                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        pic_UI = new javax.swing.JLabel();
        sldr_UI = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_UserID = new javax.swing.JTextField();
        txt_Opis = new javax.swing.JTextField();
        txt_Iznos = new javax.swing.JTextField();
        lbl_Ime = new javax.swing.JLabel();
        lbl_Prezime = new javax.swing.JLabel();
        b_Potvrda = new javax.swing.JButton();
        lbl_Izlaz = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panelCekanje = new javax.swing.JPanel();
        naCekanjuLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_PregledUplata = new javax.swing.JTable();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(26, 83, 92));

        pic_UI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/pic_money.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pic_UI)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(pic_UI)
                .addGap(35, 35, 35))
        );

        sldr_UI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sldr_UIMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Uplata");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Isplata");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("User ID:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Iznos:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Opis:");

        txt_UserID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_UserID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_UserIDFocusLost(evt);
            }
        });
        txt_UserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UserIDKeyTyped(evt);
            }
        });

        txt_Opis.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        txt_Iznos.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Iznos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IznosKeyTyped(evt);
            }
        });

        lbl_Ime.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_Ime.setText("Ime");

        lbl_Prezime.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lbl_Prezime.setText("Prezime");

        b_Potvrda.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        b_Potvrda.setText("Potvrda");
        b_Potvrda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_PotvrdaActionPerformed(evt);
            }
        });

        lbl_Izlaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/htr/Images/rsz_exit.png"))); // NOI18N
        lbl_Izlaz.setToolTipText("");
        lbl_Izlaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_IzlazMouseClicked(evt);
            }
        });

        panelCekanje.setBackground(new java.awt.Color(233, 196, 106));

        naCekanjuLBL.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        naCekanjuLBL.setForeground(new java.awt.Color(255, 255, 255));
        naCekanjuLBL.setText("Čeka se admin za odobrenje:");

        tbl_PregledUplata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_PregledUplata);

        javax.swing.GroupLayout panelCekanjeLayout = new javax.swing.GroupLayout(panelCekanje);
        panelCekanje.setLayout(panelCekanjeLayout);
        panelCekanjeLayout.setHorizontalGroup(
            panelCekanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(panelCekanjeLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(naCekanjuLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCekanjeLayout.setVerticalGroup(
            panelCekanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekanjeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(naCekanjuLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(panelCekanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Opis)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_Ime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_Prezime)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Iznos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_Potvrda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldr_UI, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(lbl_Izlaz))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(sldr_UI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Izlaz)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Ime)
                            .addComponent(lbl_Prezime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Opis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txt_Iznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b_Potvrda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelCekanje, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UserIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UserIDKeyTyped
        ZabraniSlova(evt);
    }//GEN-LAST:event_txt_UserIDKeyTyped

    private void txt_IznosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IznosKeyTyped
        // TODO add your handling code here:
        ZabraniSlova(evt);
    }//GEN-LAST:event_txt_IznosKeyTyped

    private void PunjenjeTablica() {
        RS = CALIzb.main(Conn, "select F04UIID ID, F04IZN Iznos, F04OPI Opis, (CASE WHEN F04UI = 0 THEN 'Isplata' ELSE 'Uplata' END) 'Uplata/Isplata',  CASE WHEN F04STA = '0' THEN 'Nije obrađeno' ELSE 'Obrađeno' END AS 'Status' from User_UI_Odobrenje where F04UID = '" + txt_UserID.getText().trim() + "'");
        tbl_PregledUplata.setModel(DbUtils.resultSetToTableModel(RS));
    }

    private void lbl_IzlazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_IzlazMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lbl_IzlazMouseClicked

    private void txt_UserIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_UserIDFocusLost
        // TODO add your handling code here:
        GetUser(Integer.parseInt(txt_UserID.getText().trim()));
    }//GEN-LAST:event_txt_UserIDFocusLost

    private void sldr_UIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldr_UIMouseReleased
        // TODO add your handling code here:
        if (sldr_UI.getValue() < 50) {
            sldr_UI.setValue(0);
        }
        if (sldr_UI.getValue() > 50) {
            sldr_UI.setValue(100);
        }
    }//GEN-LAST:event_sldr_UIMouseReleased

    private void b_PotvrdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_PotvrdaActionPerformed
        // TODO add your handling code here:
        //Hvatamo zadnji ID

        RS = CALIzb.main(Conn, "SELECT TOP 1 F04UIID FROM User_UI_Odobrenje ORDER BY F04UIID DESC");
        try {
            while (RS.next()) {
                myNextID = RS.getInt("F04UIID");
                myNextID += 1;
            }
            if (myNextID == 0) {
                myNextID += 1;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //Provjera i upis
        try {
            if (sldr_UI.getValue() == 0 || sldr_UI.getValue() == 100) {
                if (!txt_UserID.getText().trim().equals("")) {
                    if (!txt_Iznos.getText().trim().equals("")) {
                        if (sldr_UI.getValue() == 0) {
                            double myEntVal = Double.parseDouble(txt_Iznos.getText().trim());
                            if (myEntVal <= UserBalance) {
                                RS = CALIzb.main(Conn, "insert into User_UI_Odobrenje values ('" + myNextID + "', '" + txt_Iznos.getText().trim() + "', '0', '" + txt_Opis.getText().trim() + "', GETDATE(), '" + userUsername + "', 'Split', '" + myUserID + "','0')");
                                dispose();
                            } else {
                                System.out.println("Nemate dovoljno na racunu!");
                            }
                        } else if (sldr_UI.getValue() == 100) {
                            RS = CALIzb.main(Conn, "insert into User_UI_Odobrenje values ('" + myNextID + "', '" + txt_Iznos.getText().trim() + "', '1', '" + txt_Opis.getText().trim() + "', GETDATE(), ' ', ' ', '" + myUserID + "','0')");
                            dispose();
                        }
                    }
                }
            }
        } catch (Exception f) {
            f.printStackTrace();
        }
    }//GEN-LAST:event_b_PotvrdaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Potvrda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Ime;
    private javax.swing.JLabel lbl_Izlaz;
    private javax.swing.JLabel lbl_Prezime;
    private javax.swing.JLabel naCekanjuLBL;
    private javax.swing.JPanel panelCekanje;
    private javax.swing.JLabel pic_UI;
    private javax.swing.JSlider sldr_UI;
    private javax.swing.JTable tbl_PregledUplata;
    private javax.swing.JTextField txt_Iznos;
    private javax.swing.JTextField txt_Opis;
    private javax.swing.JTextField txt_UserID;
    // End of variables declaration//GEN-END:variables
}
